name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    
    - name: Run tests
      run: |
        python tests.py
      
    - name: Check test result
      if: ${{ failure() }}
      run: |
        echo "Tests failed. Please check the output."
        exit 1
